import streamlit as st
import joblib
import pandas as pd
import numpy as np

# Load the AI brain you built with Jules
# These artifacts were generated by predict_maintenance.py
model = joblib.load('maintenance_model.joblib')
encoder = joblib.load('label_encoder.joblib')

st.title("🛠️ Mechatronics Predictive Maintenance")
st.markdown("Use the sliders below to simulate sensor data and predict machine health.")

# Sidebar for inputs
st.sidebar.header("Sensor Input Panel")
torque = st.sidebar.slider("Torque [Nm]", 0, 80, 40)
rpm = st.sidebar.slider("Rotational Speed [rpm]", 500, 3000, 1500)
tool_wear = st.sidebar.slider("Tool Wear [min]", 0, 250, 50)

# Safety Settings Sidebar
st.sidebar.markdown("---")
st.sidebar.header("Safety Settings")
# Risk Sensitivity adjusts the probability threshold for failure prediction
sensitivity = st.sidebar.slider("Risk Sensitivity (Threshold)", 0.1, 0.9, 0.5)

# Physics-Informed Feature Engineering
# Power (kW) = (Torque * RPM) / 9550
power_kw = (torque * rpm) / 9550
# Temperature Difference (Assumption: Air Temp=300K, Process Temp=310K)
air_temp = 300.0
proc_temp = 310.0
temp_diff = proc_temp - air_temp
# Torque-Wear Interaction
torque_wear = torque * tool_wear

# Create the data for the AI to read (9 features total)
input_data = pd.DataFrame([[0, air_temp, proc_temp, rpm, torque, tool_wear, power_kw, temp_diff, torque_wear]],
                          columns=['Type', 'Air temperature [K]', 'Process temperature [K]',
                                   'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]',
                                   'Power_kW', 'Temp_Difference', 'Torque_Wear_Product'])

# Make the prediction using probability threshold
probabilities = model.predict_proba(input_data)[0][1] # Get the % risk of failure (class 1)

# Display results
st.subheader("Machine Status")
if probabilities >= sensitivity:
    st.error(f"⚠️ FAILURE PREDICTED (Risk Score: {probabilities * 100:.1f}%)")
    st.markdown(f"**Action Required:** Threshold set at {sensitivity*100:.0f}%. AI is highly confident in failure.")
else:
    st.success(f"✅ SYSTEM HEALTHY (Risk Score: {probabilities * 100:.1f}%)")
    st.markdown(f"**Status:** Operating within safe limits for current sensitivity ({sensitivity*100:.0f}%).")

# Add a simple gauge-like metric
st.markdown("---")
col1, col2, col3 = st.columns(3)
col1.metric("Current Torque", f"{torque} Nm", delta=f"{torque-40} Nm" if torque > 40 else None)
col2.metric("Power Output", f"{power_kw:.2f} kW")
col3.metric("Risk Level", f"{probabilities * 100:.1f}%")

# Mathematical Explanation for User
with st.expander("How does this work? (The Math)"):
    st.write("""
    1. **Feature Engineering**: We calculate **Power (kW)** and **Torque-Wear interaction** because failure often isn't
       caused by one sensor alone, but by their combination.
    2. **Probability Threshold**: Instead of a simple Yes/No, we look at the 'confidence' of the AI.
       If you set sensitivity to 0.1 (10%), the AI will warn you even if it's only slightly suspicious.
    3. **Random Forest**: The AI uses 500 decision trees to vote on the outcome. The Risk Score is the
       percentage of trees that voted 'Failure'.
    """)
